const PERMISSIONS = require("./permissions");

const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ROLE_UPDATE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  manager: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,

    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  support: [PERMISSIONS.USERS_READ, PERMISSIONS.PROFILE_READ],

  user: [PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE],
};

module.exports = ROLE_PERMISSIONS;
